name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential alsa-tools libasound2-dev alsa-utils alsa-oss pavucontrol autoconf automake libtool pkg-config libao-dev libao-common android-tools-adb android-tools-fastboot subversion mingw-w64 gawk mawk libpulse-dev libcurl4 pulseaudio pulseaudio-utils cmake gcc-multilib g++-multilib musl musl-tools libsdl2-mixer-2.0-0 libsdl2-mixer-dev

    - name: sc68-svn
      run: |
        mkdir libs
        mkdir libs/_compiled
        mkdir libs/sc68-svn
        mkdir libs/sc68-svn/_build
        cd libs
        git clone https://github.com/madler/zlib.git
        cd sc68-svn
        svn checkout http://svn.code.sf.net/p/sc68/code/ sc68
        cd sc68
        ./tools/svn-bootstrap.sh
      shell: sh

    - name: win32-x86_64
      run: |
        export DIST=x86_64-w64-mingw32
        cd libs
        cd zlib
        mkdir build
        cd build
        mkdir $DIST
        cd $DIST
        ../../configure --prefix=$DIST --static
        make
        pwd
        dir
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC LDFLAGS="-L../../../zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
      shell: sh

    - name: win32-x86
      run: |
        export DIST=i686-w64-mingw32
        cd libs
        cd zlib
        mkdir build
        cd build
        mkdir $DIST
        cd $DIST
        ../../configure --prefix=$DIST --static
        make
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC LDFLAGS="-L../../../zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
      shell: sh

    - name: linux-x86_64
      run: |
        export DIST=x86_64-pc-linux-gnu
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
      shell: sh
      
