name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-windows-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential alsa-tools libasound2-dev alsa-utils alsa-oss pavucontrol autoconf automake libtool pkg-config libao-dev libao-common android-tools-adb android-tools-fastboot subversion mingw-w64 gawk mawk libpulse-dev libcurl4 pulseaudio pulseaudio-utils cmake gcc-multilib g++-multilib musl musl-tools libsdl2-mixer-2.0-0 libsdl2-mixer-dev

    - name: Android NDK
      uses: nttld/setup-ndk@v1.2.0
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: true
        local-cache: true

    - name: libs
      run: |
        mkdir libs
        mkdir libs/_compiled
        mkdir libs/sc68-svn
        mkdir libs/sc68-svn/_build
        mkdir libs/portaudio
        cd libs/portaudio
        mkdir _build
        git clone https://github.com/croissanne/portaudio_opensles.git
        cd ..
        git clone https://github.com/madler/zlib.git
        cd sc68-svn
        svn checkout http://svn.code.sf.net/p/sc68/code/ sc68
        cd sc68
        ./tools/svn-bootstrap.sh

    - name: linux-x86_64
      run: |
        export DIST=x86_64-pc-linux-gnu
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CFLAGS=-fPIC
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/

    - name: arm64-v8a
      run: |
        export DIST=aarch64-linux-androideabi22
        export TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
        export PATH=$PATH:$TOOLCHAIN
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --enable-static --disable-shared CC=aarch64-linux-android22-clang CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CC=aarch64-linux-android22-clang CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC LDFLAGS='-pthread' CC=aarch64-linux-android22-clang
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: armeabi-v7a
      run: |
        export DIST=armv7a-linux-androideabi22
        export TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
        export PATH=$PATH:$TOOLCHAIN
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC LDFLAGS='-pthread'
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: win32-x86_64
      run: |
        export DIST=x86_64-w64-mingw32
        mkdir libs/_compiled/$DIST
        cd libs
        cd zlib
        mkdir build
        cd build
        mkdir $DIST
        cd $DIST
        ../../configure --prefix=$DIST --static
        make
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC LDFLAGS="-L/home/runner/work/sc68/sc68/libs/zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --enable-static --disable-shared CFLAGS=-fPIC --disable-external-libs
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/

    - name: win32-x86
      run: |
        export DIST=i686-w64-mingw32
        mkdir libs/_compiled/$DIST
        cd libs/zlib/build
        mkdir $DIST
        cd $DIST
        ../../configure --prefix=$DIST --static
        make
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC LDFLAGS="-L/home/runner/work/sc68/sc68/libs/zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --enable-static --disable-shared CFLAGS=-fPIC --disable-external-libs
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/

  darwin:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        brew install autoconf automake gawk mawk

    - name: libs
      run: |
        mkdir libs
        mkdir libs/_compiled
        mkdir libs/sc68-svn
        mkdir libs/sc68-svn/_build
        mkdir libs/portaudio
        cd libs/portaudio
        mkdir _build
        git clone https://github.com/croissanne/portaudio_opensles.git
        cd ../sc68-svn
        svn checkout http://svn.code.sf.net/p/sc68/code/ sc68
        cd sc68
        ./tools/svn-bootstrap.sh

    - name: compile
      run: |
        export DIST=x86_64-apple-darwin11
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared --disable-mac-universal CC=clang CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared --disable-mac-universal CC=clang CFLAGS=-fPIC
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
