name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-windows-android:
    runs-on: ubuntu-latest

    steps:
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential alsa-tools libasound2-dev alsa-utils alsa-oss pavucontrol autoconf automake libtool pkg-config libao-dev libao-common android-tools-adb android-tools-fastboot subversion mingw-w64 gawk mawk libpulse-dev libcurl4 pulseaudio pulseaudio-utils cmake gcc-multilib g++-multilib musl musl-tools libsdl2-mixer-2.0-0 libsdl2-mixer-dev

    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Android NDK
      uses: nttld/setup-ndk@v1.2.0
      id: setup-ndk
      with:
        ndk-version: r25c
        add-to-path: true
        local-cache: true

    - name: libs
      run: |
        mkdir output
        mkdir libs
        mkdir libs/_compiled
        mkdir libs/sc68-svn
        mkdir libs/sc68-svn/_build
        mkdir libs/portaudio
        cd libs/portaudio
        mkdir _build
        git clone https://github.com/croissanne/portaudio_opensles.git
        cd ..
        git clone https://github.com/madler/zlib.git
        cd sc68-svn
        svn checkout http://svn.code.sf.net/p/sc68/code/ sc68
        cd sc68
        ./tools/svn-bootstrap.sh

    - name: linux-x86-64
      run: |
        DIST=x86_64-pc-linux-gnu
        DST_NAME=sc68
        DST_GCC=gcc
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CFLAGS=-fPIC
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../..
        mkdir bin
        mkdir bin/$DIST
        cd bin/$DIST
        $DST_GCC -std=c99 $DST_INCLUDES -O3 -c -fPIC ../../$DST_NAME"_player.c"
        $DST_GCC -s -L$DST_LIBS_DIR/_compiled/$DIST -shared -o lib$DST_NAME.so $DST_NAME"_player.o" -Wl,-Bstatic $DST_LIBS -lportaudio -Wl,-Bdynamic -pthread -lm -lz -lasound
        cd ../..
        mkdir output/linux-x86-64
        cp bin/$DIST/libsc68.so output/linux-x86-64/

    - name: linux-x86-32
      run: |
        DIST=i686-pc-linux-gnu
        DST_NAME=sc68
        DST_GCC=gcc
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        mkdir libs/_compiled/$DIST
        cd libs
        cd zlib
        mkdir build
        cd build
        mkdir $DIST
        cd $DIST
        CC=i686-linux-gnu-gcc CFLAGS="-m32" ../../configure --prefix=$DIST --static
        make
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS="-fPIC -m32"
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS="-fPIC -m32" LDFLAGS="-L/home/runner/work/sc68/sc68/libs/zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CFLAGS="-fPIC -m32"
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../..
        mkdir bin
        mkdir bin/$DIST
        cd bin/$DIST
        $DST_GCC -std=c99 $DST_INCLUDES -O3 -c -fPIC -m32 ../../$DST_NAME"_player.c"
        $DST_GCC -s -L$DST_LIBS_DIR/_compiled/$DIST -shared -o lib$DST_NAME.so $DST_NAME"_player.o" -Wl,-Bstatic $DST_LIBS -lportaudio -Wl,-Bdynamic -pthread -lm -lz -lasound
        cd ../..
        mkdir output/linux-x86
        cp bin/$DIST/libsc68.so output/linux-x86/

    - name: arm64-v8a
      run: |
        DIST=aarch64-linux-androideabi22
        DST_NAME=sc68
        DST_GCC=aarch64-linux-android22-clang
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
        export PATH=$PATH:$TOOLCHAIN
        touch ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/22/libpthread.a
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --enable-static --disable-shared CC=aarch64-linux-android22-clang CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CC=aarch64-linux-android22-clang CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CFLAGS=-fPIC CC=aarch64-linux-android22-clang LDFLAGS='-pthread'
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../../bin
        mkdir $DIST
        cd $DIST
        $DST_GCC -std=c99 -I${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include $DST_INCLUDES -O3 -c -fPIC ../../$DST_NAME"_player.c"
        $DST_GCC -s -L$DST_LIBS_DIR/_compiled/$DIST -shared -o lib$DST_NAME.so $DST_NAME"_player.o" -Wl,-Bstatic $DST_LIBS -lportaudio -Wl,-Bdynamic -lm -lz -lOpenSLES
        cd ../..
        mkdir output/arm64-v8a
        cp bin/$DIST/libsc68.so output/arm64-v8a/
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: armeabi-v7a
      run: |
        DIST=armv7a-linux-androideabi22
        DST_NAME=sc68
        DST_GCC=armv7a-linux-androideabi22-clang
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        export TOOLCHAIN=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin
        export PATH=$PATH:$TOOLCHAIN
        touch ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/22/libpthread.a
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CC=$DIST-clang CFLAGS=-fPIC LDFLAGS='-pthread'
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../../bin
        mkdir $DIST
        cd $DIST
        $DST_GCC -std=c99 -I${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include $DST_INCLUDES -O3 -c -fPIC ../../$DST_NAME"_player.c"
        $DST_GCC -s -L$DST_LIBS_DIR/_compiled/$DIST -shared -o lib$DST_NAME.so $DST_NAME"_player.o" -Wl,-Bstatic $DST_LIBS -lportaudio -Wl,-Bdynamic -lm -lz -lOpenSLES
        cd ../..
        mkdir output/armeabi-v7a
        cp bin/$DIST/libsc68.so output/armeabi-v7a/
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: win32-x86-64
      run: |
        DIST=x86_64-w64-mingw32
        DST_NAME=sc68
        DST_GCC=x86_64-w64-mingw32-gcc
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        mkdir libs/_compiled/$DIST
        cd libs/zlib/build
        mkdir $DIST
        cd $DIST
        ../../configure --prefix=$DIST --static
        make
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC LDFLAGS="-L/home/runner/work/sc68/sc68/libs/zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CFLAGS=-fPIC --disable-external-libs
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../../bin
        mkdir $DIST
        cd $DIST
        $DST_GCC -std=c99 -D_WIN64 $DST_INCLUDES -O3 -c -fPIC ../../$DST_NAME"_player.c"
        $DST_GCC -s -L$DST_LIBS_DIR/_compiled/$DIST -shared -o $DST_NAME.dll $DST_NAME"_player.o" -Wl,-Bstatic $DST_LIBS -lportaudio -Wl,-Bdynamic -lm -lwinmm
        cd ../..
        mkdir output/win32-x86-64
        cp bin/$DIST/sc68.dll output/win32-x86-64/

    - name: win32-x86-32
      run: |
        DIST=i686-w64-mingw32
        DST_NAME=sc68
        DST_GCC=i686-w64-mingw32-gcc
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        mkdir libs/_compiled/$DIST
        cd libs/zlib/build
        mkdir $DIST
        cd $DIST
        ../../configure --prefix=$DIST --static
        make
        cd ../../../sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        cd ..
        ../../sc68/configure --host=$DIST --without-ao --enable-static --disable-shared CFLAGS=-fPIC LDFLAGS="-L/home/runner/work/sc68/sc68/libs/zlib/build/$DIST/"
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --host=$DIST --enable-static --disable-shared CFLAGS=-fPIC --disable-external-libs
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../../bin
        mkdir $DIST
        cd $DIST
        $DST_GCC -std=c99 -D_WIN32 $DST_INCLUDES -O3 -c -fPIC ../../$DST_NAME"_player.c"
        $DST_GCC -s -L$DST_LIBS_DIR/_compiled/$DIST -shared -o $DST_NAME.dll $DST_NAME"_player.o" -Wl,-Bstatic $DST_LIBS -lportaudio -Wl,-Bdynamic -lm -lwinmm
        cd ../..
        mkdir output/win32-x86
        cp bin/$DIST/sc68.dll output/win32-x86/

    - name: Deploy
      uses: dennisameling/ftp-upload-action@v1.0.10
      with:
        server: ftp.b3dgs.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local_dir: output/
        server_dir: /
        secure: false

  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0

    - name: Dependencies
      run: |
        brew install autoconf automake gawk mawk

    - name: libs
      run: |
        mkdir output
        mkdir libs
        mkdir libs/_compiled
        mkdir libs/sc68-svn
        mkdir libs/sc68-svn/_build
        mkdir libs/portaudio
        cd libs/portaudio
        mkdir _build
        git clone https://github.com/croissanne/portaudio_opensles.git
        cd ../sc68-svn
        svn checkout http://svn.code.sf.net/p/sc68/code/ sc68
        cd sc68
        ./tools/svn-bootstrap.sh

    - name: macos-x86-64
      run: |
        DIST=x86_64-apple-darwin11
        DST_NAME=sc68
        DST_GCC=clang
        DST_LIBS_DIR=$(pwd)/libs
        DST_INCLUDES="-I$DST_LIBS_DIR/portaudio/portaudio_opensles/include -I$DST_LIBS_DIR/sc68-svn/sc68/file68 -I$DST_LIBS_DIR/sc68-svn/sc68/libsc68"
        DST_LIBS="-lsc68 -lfile68 -lunice68"
        mkdir libs/_compiled/$DIST
        cd libs/sc68-svn/_build
        mkdir $DIST
        cd $DIST
        mkdir as68
        cd as68
        ../../../sc68/as68/configure --without-ao --enable-static --disable-shared CFLAGS=-fPIC
        make
        make install
        cd ..
        ../../sc68/configure --without-ao --enable-static --disable-shared --disable-mac-universal CC=clang CFLAGS=-fPIC
        make
        cp libsc68/.libs/libsc68.a ../../../_compiled/$DIST/
        cp file68/.libs/libfile68.a ../../../_compiled/$DIST/
        cp unice68/.libs/libunice68.a ../../../_compiled/$DIST/
        cd ../../..
        mkdir portaudio/_build/$DIST
        cd portaudio/_build/$DIST
        ../../portaudio_opensles/configure --enable-static --disable-shared --disable-mac-universal CC=clang CFLAGS=-fPIC
        make
        cp lib/.libs/libportaudio.a ../../../_compiled/$DIST/
        cd ../../../..
        mkdir bin
        mkdir bin/$DIST
        cd bin/$DIST
        $DST_GCC -std=c99 $DST_INCLUDES -O3 -c -fPIC ../../$DST_NAME"_player.c"
        $DST_GCC -dynamiclib -framework CoreAudio -framework AudioToolbox -framework AudioUnit -framework CoreFoundation -framework CoreServices -L$DST_LIBS_DIR/_compiled/$DIST -o lib$DST_NAME.dylib $DST_NAME"_player.o" -lcurl $DST_LIBS -lportaudio -pthread -lm -lz
        cd ../..
        mkdir output/darwin-x86-64
        ls bin/$DIST/
        cp bin/$DIST/libsc68.dylib output/darwin-x86-64/

    - name: Deploy
      uses: dennisameling/ftp-upload-action@v1.0.10
      with:
        server: ftp.b3dgs.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local_dir: output/
        server_dir: /
        secure: false
